# Generated by Django 2.0.5 on 2018-12-27 01:45

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_cover', models.ImageField(default='video_bg/bg-1.png', upload_to='news/%Y/%m', verbose_name='封面')),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='新闻内容')),
            ],
        ),
    ]
