# Generated by Django 2.0.5 on 2018-12-26 02:19

import DjangoUeditor.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='公司名字')),
                ('detail', DjangoUeditor.forms.UEditorField(default='', verbose_name='公司详情')),
            ],
            options={
                'verbose_name': '公司简介',
                'verbose_name_plural': '公司简介',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='首页视频')),
                ('video_bg', models.ImageField(default='video_bg/bg-1.png', upload_to='video_bg/%Y/%m', verbose_name='视频背景')),
            ],
        ),
    ]
