# Generated by Django 2.0.5 on 2018-12-27 07:23

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit_name', models.CharField(max_length=100, verbose_name='职位')),
                ('recruit_term', DjangoUeditor.models.UEditorField(default='', verbose_name='任职要求')),
            ],
        ),
    ]
