# Generated by Django 2.0.5 on 2018-12-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_recruit_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruit',
            options={'verbose_name': '招贤纳士', 'verbose_name_plural': '招贤纳士'},
        ),
    ]
